"""
loader.py

Central resource loader for the AML Agent backend.

Loads ML models and datasets once at application startup and keeps them
cached as module-level singletons. All other backend modules should import
resources from here rather than loading files directly.

Loaded resources:
    - XGBoost classifier          (models/xgb_model.pkl)
    - Isolation Forest model      (models/isolation_forest.pkl)
    - Label encoders              (models/label_encoders.pkl)
    - Feature matrix              (data/features.csv)
    - Pre-computed risk scores    (data/risk_predictions.csv)
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, List, Optional

import joblib
import pandas as pd

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths (resolved relative to project root, not the working directory)
# ---------------------------------------------------------------------------

PROJECT_ROOT: Path = Path(__file__).resolve().parent.parent
MODELS_DIR: Path = PROJECT_ROOT / "models"
DATA_DIR: Path = PROJECT_ROOT / "data"

XGB_MODEL_PATH: Path = MODELS_DIR / "xgb_model.pkl"
ISOLATION_FOREST_PATH: Path = MODELS_DIR / "isolation_forest.pkl"
LABEL_ENCODERS_PATH: Path = MODELS_DIR / "label_encoders.pkl"
FEATURES_PATH: Path = DATA_DIR / "features.csv"
RISK_PREDICTIONS_PATH: Path = DATA_DIR / "risk_predictions.csv"

# ---------------------------------------------------------------------------
# Constants derived from the feature matrix after loading
# ---------------------------------------------------------------------------

TARGET_COLUMN: str = "Is Laundering"
FEATURE_COLUMNS: List[str] = []

# ---------------------------------------------------------------------------
# Cached singletons (None until load_all() is called)
# ---------------------------------------------------------------------------

_xgb_model: Optional[Any] = None
_isolation_forest: Optional[Any] = None
_label_encoders: Optional[Dict[str, Any]] = None
_features_df: Optional[pd.DataFrame] = None
_risk_predictions_df: Optional[pd.DataFrame] = None
_loaded: bool = False


def _require_file(path: Path) -> None:
    """Raise FileNotFoundError with a clear message if a resource is missing."""
    if not path.is_file():
        raise FileNotFoundError(
            f"Required AML resource not found: {path}. "
            "Ensure models and data have been generated by the ML pipeline."
        )


def load_all(*, force: bool = False) -> None:
    """
    Load all models and datasets into the module cache.

    Safe to call multiple times; subsequent calls are no-ops unless
    ``force=True`` is passed.

    Args:
        force: When True, reload all resources even if already cached.

    Raises:
        FileNotFoundError: If any required model or data file is missing.
        Exception: Propagates joblib/pandas errors from corrupt files.
    """
    global _xgb_model, _isolation_forest, _label_encoders
    global _features_df, _risk_predictions_df, _loaded, FEATURE_COLUMNS

    if _loaded and not force:
        logger.debug("AML resources already loaded; skipping.")
        return

    logger.info("Loading AML resources from %s", PROJECT_ROOT)

    for path in (
        XGB_MODEL_PATH,
        ISOLATION_FOREST_PATH,
        LABEL_ENCODERS_PATH,
        FEATURES_PATH,
        RISK_PREDICTIONS_PATH,
    ):
        _require_file(path)

    logger.info("Loading XGBoost model …")
    _xgb_model = joblib.load(XGB_MODEL_PATH)

    logger.info("Loading Isolation Forest model …")
    _isolation_forest = joblib.load(ISOLATION_FOREST_PATH)

    logger.info("Loading label encoders …")
    _label_encoders = joblib.load(LABEL_ENCODERS_PATH)

    logger.info("Loading features dataset …")
    _features_df = pd.read_csv(FEATURES_PATH)

    logger.info("Loading risk predictions dataset …")
    _risk_predictions_df = pd.read_csv(RISK_PREDICTIONS_PATH)

    FEATURE_COLUMNS = [
        column
        for column in _features_df.columns
        if column != TARGET_COLUMN
    ]

    _loaded = True

    logger.info(
        "AML resources loaded — features: %s rows × %s cols, "
        "risk_predictions: %s rows",
        len(_features_df),
        len(_features_df.columns),
        len(_risk_predictions_df),
    )


def _ensure_loaded() -> None:
    """Load resources on first access if startup has not called load_all()."""
    if not _loaded:
        load_all()


# ---------------------------------------------------------------------------
# Public accessors
# ---------------------------------------------------------------------------


def get_xgb_model() -> Any:
    """Return the cached XGBoost classifier."""
    _ensure_loaded()
    return _xgb_model


def get_isolation_forest() -> Any:
    """Return the cached Isolation Forest model."""
    _ensure_loaded()
    return _isolation_forest


def get_label_encoders() -> Dict[str, Any]:
    """Return the cached sklearn LabelEncoder dictionary."""
    _ensure_loaded()
    return _label_encoders  # type: ignore[return-value]


def get_features_df() -> pd.DataFrame:
    """Return the cached feature matrix (includes target column)."""
    _ensure_loaded()
    return _features_df.copy(deep=False)  # type: ignore[return-value]


def get_risk_predictions_df() -> pd.DataFrame:
    """Return the cached pre-computed risk predictions."""
    _ensure_loaded()
    return _risk_predictions_df.copy(deep=False)  # type: ignore[return-value]


def get_feature_columns() -> List[str]:
    """Return the list of ML feature column names (excludes target)."""
    _ensure_loaded()
    return list(FEATURE_COLUMNS)


def is_loaded() -> bool:
    """Return True if all resources have been loaded into the cache."""
    return _loaded


__all__ = [
    "PROJECT_ROOT",
    "MODELS_DIR",
    "DATA_DIR",
    "TARGET_COLUMN",
    "FEATURE_COLUMNS",
    "load_all",
    "get_xgb_model",
    "get_isolation_forest",
    "get_label_encoders",
    "get_features_df",
    "get_risk_predictions_df",
    "get_feature_columns",
    "is_loaded",
]
